openapi: 3.0.0
info:
  title: Customer Service Rating
  description: |
    API that returns representative current rating and post new rating
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /customer_service/representative/{reps_id}/rating:
    post:
      summary: Rate a representative’s chat session
      parameters:
        - name: reps_id
          in: path
          required: true
          description: Identifier of the representative.
          schema:
            type: string
          example: 0ceac7d3-ab45-460a-a561-b56b3b7cd1ca

      requestBody:
        required: true
        content:
          application/json:
            example: [
              {
                session_id: 042819-004,
                rating: 2
              }
            ]
            
            schema:
              type: array
              items:
                type: object
                properties:
                  session_id:
                    type: string
                    example: 042519-223
                  rating:
                    type: integer
                    minimum: 1
                    maximum: 5
                    example: 3

      responses:
        "200": # status code
          description: Rating is recorded successfully
          content:
            application/json:
              schema:
                type: string
                example: 
                  "Rating is recorded. Thank you!"
        "400": 
          description: Invalid rating
          content:
            application/json:
              schema:
                type: string
                example:
                  "Rating choice is invalid"
    get:
      summary: look up representative information
      parameters:
        - name: reps_id
          in: path
          required: true
          description: Identifier of the representative.
          schema:
            type: string
          example: 68f0d4ae-50f7-4de8-93a9-7d1d7d64bedb

      responses:
        "200": # status code
          description: return current rating successfully 
          content:
            application/json:
              example: [
                {
                reps_id: ad4e8413-c6a5-4563-b665-a194abf570be,
                rating: 3.5
                }
              ]

              schema:
                type: array
                items:
                  properties:
                    reps_id:
                      type: string
                      example: 72ad52e0-cad6-4927-922a-2b4ed48f4d8e
                    rating:
                      type: number
                      example: 4.3
        "404": 
          description: requested content not found
          content:
            application/json:
              schema:
                type: string
                example: 
                  "Requested information is not available"
                    
                
                  
